workflows:
  unity_ios:
    name: Unity ARKit App for iOS
    environment:
      vars:
        UNITY_PROJECT_PATH: "."  # Root folder of your Unity project
        OUTPUT_PATH: "$CM_BUILD_DIR/Build"
        UNITY_EXECUTABLE_PATH: "/Applications/Unity/Hub/Editor/2022.3.0f1/Unity.app/Contents/MacOS/Unity"
        UNITY_LICENSE: $UNITY_ACTIVATION_FILES
      xcode: latest
    triggering:
      events:
        - push
        - pull_request
    scripts:
      - name: Install Unity and Unity Hub
        script: |
          # Install Unity Hub (necessary step before installing Unity)
          brew install --cask unity-hub
          
          # Install specific Unity version
          /Applications/Unity/Hub.app/Contents/MacOS/UnityHub --headless install --version 2022.3.0f1 --module iOS

      - name: Build Unity project for iOS
        script: |
          $UNITY_EXECUTABLE_PATH \
          -batchmode \
          -nographics \
          -quit \
          -projectPath $UNITY_PROJECT_PATH \
          -buildTarget iOS \
          -executeMethod BuildScript.PerformBuild \
          -customBuildPath $OUTPUT_PATH

      - name: Build and export iOS app
        script: |
          cd $OUTPUT_PATH
          xcodebuild clean archive \
          -archivePath $CM_BUILD_DIR/Build.xcarchive \
          -scheme Unity-iPhone \
          -sdk iphoneos \
          CODE_SIGN_IDENTITY="$CM_CODE_SIGN_IDENTITY" \
          PROVISIONING_PROFILE_SPECIFIER="$CM_PROVISIONING_PROFILE"
          
          xcodebuild -exportArchive \
          -archivePath $CM_BUILD_DIR/Build.xcarchive \
          -exportPath $CM_BUILD_DIR/Export \
          -exportOptionsPlist exportOptions.plist

    artifacts:
      - $CM_BUILD_DIR/Export/*.ipa

