workflows:
  unity-ios:
    name: Unity iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - apple_credentials  # Store Apple Developer credentials in Codemagic
    triggering:
      events:
        - push
    scripts:
      - name: Install Unity Hub
        script: |
          brew tap homebrew/cask
          brew install --cask unity-hub
      - name: Download Unity Installer
        script: |
          curl -L -o Unity-6000.0.32f1.pkg "https://drive.google.com/uc?export=download&id=1aE3ZRPxFW7C-B9IeM4-tu4l96K-6w7B2"
      - name: Verify Unity Installer Download
        script: |
          if [ -f Unity-6000.0.32f1.pkg ]; then
            echo "Unity installer downloaded successfully."
            ls -lh Unity-6000.0.32f1.pkg  # Check file size
          else
            echo "Failed to download Unity installer."
            exit 1
          fi
      - name: Install Unity
        script: |
          sudo installer -pkg Unity-6000.0.32f1.pkg -target /
      - name: Verify Unity Installation
        script: |
          ls /Applications/Unity/Hub/Editor/6000.0.32f1/Unity.app/Contents/MacOS/Unity
      - name: Build Unity project
        script: |
          /Applications/Unity/Hub/Editor/6000.0.32f1/Unity.app/Contents/MacOS/Unity \
          -quit -batchmode -nographics -executeMethod BuildScript.BuildiOS \
          -projectPath . -logFile
      - name: Build Xcode project
        script: |
          mkdir -p $HOME/build  # Ensure the archive directory exists
          echo "Building Xcode project..."
          xcodebuild -project Unity-iPhone.xcodeproj \
          -scheme Unity-iPhone \
          -sdk iphoneos \
          -configuration Release \
          archive -archivePath $HOME/build/YourGame.xcarchive | tee xcodebuild.log
          if [ $? -eq 0 ]; then
            echo "Xcode build succeeded."
          else
            echo "Xcode build failed. Check xcodebuild.log for details."
            exit 1
          fi
      - name: Export .ipa File
        script: |
          xcodebuild -exportArchive \
          -archivePath $HOME/build/YourGame.xcarchive \
          -exportPath $HOME/build \
          -exportOptionsPlist ExportOptions.plist
