workflows:
  unity_ios_build:
    name: Unity iOS Build
    environment:
      vars:
        UNITY_VERSION: "6000.0.32f1"  # ✅ Replace with your correct Unity version
        UNITY_DOWNLOAD_URL: "https://download.unity3d.com/download_unity/b2e806cf271c/MacEditorInstaller/Unity-6000.0.32f1.pkg"
    triggering:
      events:
        - push
    scripts:
      - name: Download and Install Unity
        script: |
          echo "Downloading Unity..."
          curl -o Unity.pkg $UNITY_DOWNLOAD_URL
          echo "Installing Unity..."
          sudo installer -pkg Unity.pkg -target /
          echo "Unity installed successfully!"

      - name: Activate Unity License
        script: |
          echo "Activating Unity License..."
          /Applications/Unity/Unity.app/Contents/MacOS/Unity \
          -batchmode -nographics -manualLicenseFile $UNITY_LICENSE_PATH \
          -logFile license_activation.log || exit 1

      - name: Build Unity Project for iOS
        script: |
          echo "Starting Unity iOS Build..."
          /Applications/Unity/Unity.app/Contents/MacOS/Unity \
          -quit -batchmode -nographics \
          -projectPath $CM_BUILD_DIR \
          -buildTarget iOS \
          -logFile build.log || exit 1

    artifacts:
      - "build/iOS/**"
