workflows:
  unity-ios:
    name: Unity iOS Build
    max_build_duration: 120  # Increased build duration
    instance_type: mac_mini_m1
    environment:
      groups:
        - apple_credentials  # Store Apple Developer credentials in Codemagic
    triggering:
      events:
        - push
    scripts:
      - name: Install Unity Hub
        script: |
          brew tap homebrew/cask
          brew install --cask unity-hub

      - name: Install gdown
        script: |
          pip install gdown

      - name: Download Unity Installer
        script: |
          FILE_ID="1aE3ZRPxFW7C-B9IeM4-tu4l96K-6w7B2"
          FILE_NAME="Unity-6000.0.32f1.pkg"
          COOKIE_FILE="cookie.txt"

          # Get the confirmation token
          CONFIRM=$(curl -s -c $COOKIE_FILE "https://drive.google.com/uc?export=download&id=${FILE_ID}" | grep -o 'confirm=[^&]*' | cut -d '=' -f 2)

          # Download the file
          curl -L -b $COOKIE_FILE "https://drive.google.com/uc?export=download&id=${FILE_ID}&confirm=${CONFIRM}" -o ${FILE_NAME}

          # Clean up
          rm -f $COOKIE_FILE

      - name: Verify Unity Installer Download
        script: |
          if [ -f Unity-6000.0.32f1.pkg ]; then
            echo "Unity installer downloaded successfully."
            ls -lh Unity-6000.0.32f1.pkg  # Check file size
            file Unity-6000.0.32f1.pkg  # Check file type
          else
            echo "Failed to download Unity installer."
            exit 1
          fi

      - name: Install Unity
        script: |
          sudo installer -pkg Unity-6000.0.32f1.pkg -target / -verbose

      - name: Check Installer Logs
        script: |
          cat /var/log/install.log | grep Unity

      - name: Verify Unity Installation
        script: |
          echo "Checking Unity installation path..."
          find /Applications -name "Unity.app"

      - name: Activate Unity License
        script: |
          echo "Activating Unity license..."
          /Applications/Unity/Unity.app/Contents/MacOS/Unity \
          -quit -batchmode -nographics \
          -manualLicenseFile ./Licenses/Unity_lic.ulf \
          -logFile license_activation.log
          if [ $? -eq 0 ]; then
            echo "Unity license activated successfully."
          else
            echo "Unity license activation failed. Check license_activation.log for details."
            exit 1
          fi

      - name: Print License Activation Log
        script: |
          if [ -f license_activation.log ]; then
            echo "License activation log:"
            cat license_activation.log
          else
            echo "License activation log file not found."
          fi

      - name: Build Unity project
        script: |
          echo "Starting Unity build..."
          /Applications/Unity/Unity.app/Contents/MacOS/Unity \
          -quit -batchmode -nographics -executeMethod BuildScript.BuildiOS \
          -projectPath . -logFile build.log
          if [ $? -eq 0 ]; then
            echo "Unity build succeeded."
            cat build.log  # Print the build log for debugging
          else
            echo "Unity build failed. Check build.log for details."
            cat build.log
            exit 1
          fi

      - name: Build Xcode project
        script: |
          mkdir -p $HOME/build  # Ensure the archive directory exists
          echo "Building Xcode project..."
          xcodebuild -project Unity-iPhone.xcodeproj \
          -scheme Unity-iPhone \
          -sdk iphoneos \
          -configuration Release \
          archive -archivePath $HOME/build/YourGame.xcarchive | tee xcodebuild.log
          if [ $? -eq 0 ]; then
            echo "Xcode build succeeded."
          else
            echo "Xcode build failed. Check xcodebuild.log for details."
            exit 1
          fi

      - name: Export .ipa File
        script: |
          xcodebuild -exportArchive \
          -archivePath $HOME/build/YourGame.xcarchive \
          -exportPath $HOME/build \
          -exportOptionsPlist ExportOptions.plist
