workflows:
  unity_ios_build:
    name: Unity iOS Build
    environment:
      vars:
        UNITY_VERSION: "6000.0.32f1"  # ✅ Replace with your actual Unity version
        UNITY_DOWNLOAD_URL: "https://download.unity3d.com/download_unity/1c867a9/MacEditorInstaller/Unity.pkg"
        UNITY_LICENSE_PATH: "$CM_BUILD_DIR/Licenses/Unity_lic.ulf"  # ✅ Correct path to license file

    triggering:
      events:
        - push

    scripts:
      - name: Download and Install Unity
        script: |
          echo "Downloading Unity..."
          curl -o Unity.pkg $UNITY_DOWNLOAD_URL
          echo "Installing Unity..."
          sudo installer -pkg Unity.pkg -target /
          echo "✅ Unity installed successfully!"
          ls -l /Applications/Unity/Hub/Editor/  # ✅ Check Unity installation

      - name: Verify License File
        script: |
          echo "Checking Unity license file..."
          if [ ! -f "$UNITY_LICENSE_PATH" ]; then
            echo "❌ License file not found! Make sure it's in 'Licenses/Unity_lic.ulf'."
            exit 1
          fi
          echo "✅ License file found and ready."

      - name: Activate Unity License
        script: |
          #!/usr/bin/env bash

          echo "Activating Unity License..."

          # Check if the license file exists
          if [ ! -f "$UNITY_LICENSE_PATH" ]; then
            echo "❌ License file missing, skipping activation!"
            exit 1
          fi

          # Ensure the Unity version is set correctly
          UNITY_PATH="/Applications/Unity/Hub/Editor/$UNITY_VERSION/Unity.app/Contents/MacOS/Unity"

          # Check if the Unity executable exists
          if [ ! -f "$UNITY_PATH" ]; then
            echo "❌ Unity executable not found at $UNITY_PATH! Please verify Unity is installed correctly."
            exit 1
          fi

          # Activate the Unity license
          $UNITY_PATH -batchmode -nographics -manualLicenseFile $UNITY_LICENSE_PATH -logFile license_activation.log || exit 1
          echo "✅ Unity License Activated"



      - name: Build Unity Project for iOS
        script: |
          echo "Starting Unity iOS Build..."
          /Applications/Unity/Hub/Editor/$UNITY_VERSION/Unity.app/Contents/MacOS/Unity \
          -quit -batchmode -nographics \
          -projectPath $CM_BUILD_DIR \
          -buildTarget iOS \
          -logFile build.log || exit 1
          echo "✅ Unity iOS Build Completed"

    artifacts:
      - "build/iOS/**"
