workflows:
  unity-ios:
    name: Unity iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - apple_credentials  # Store Apple Developer credentials in Codemagic
    triggering:
      events:
        - push
    scripts:
      - name: Install Unity
        script: |
          brew tap homebrew/cask
          brew install --cask unity-hub
          # Manually download and install Unity 6000.0.32f1
          # Ensure the path is correct in the next step
      - name: Verify Unity Installation
        script: |
          ls /Applications/Unity/Hub/Editor/6000.0.32f1/Unity.app/Contents/MacOS/Unity
      - name: Build Unity project
        script: |
          /Applications/Unity/Hub/Editor/6000.0.32f1/Unity.app/Contents/MacOS/Unity \
          -quit -batchmode -nographics -executeMethod BuildScript.BuildiOS \
          -projectPath . -logFile
      - name: Build Xcode project
        script: |
          cd Unity-iOS-Export
          xcodebuild -workspace YourGame.xcworkspace \
          -scheme YourGame \
          -sdk iphoneos \
          -configuration Release \
          archive -archivePath $HOME/build/YourGame.xcarchive
